// Code generated by "stringer -trimprefix loc -type meterLocation"; DO NOT EDIT.

package hydroserver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[locUnknown-0]
	_ = x[locGenerator-1]
	_ = x[locNeighbour-2]
	_ = x[locHere-3]
}

const _meterLocation_name = "UnknownGeneratorNeighbourHere"

var _meterLocation_index = [...]uint8{0, 7, 16, 25, 29}

func (i meterLocation) String() string {
	if i < 0 || i >= meterLocation(len(_meterLocation_index)-1) {
		return "meterLocation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _meterLocation_name[_meterLocation_index[i]:_meterLocation_index[i+1]]
}
