{
    "architecture": [
        "amd64",
        "armhf"
    ],
    "icon": "meta/go.png",
    "name": "hydro-power",
    "ports": {
        "external": {
            "webserver": {
                "negotiable": false,
                "port": "80/tcp"
            }
        }
    },
    "services": [
        {
            "caps": [
                "networking",
                "network-service"
            ],
            "description": "Hydroelectric house power controller",
            "name": "hydro",
            "start": "./bin/hydrod"
        }
    ],
    "vendor": "rogpeppe@gmail.com",
    "version": "0.0.10"
}
