name: hydro-power
version: 0
vendor: rogpeppe@gmail.com
binaries:
    bin/hydrod
ports:
    external:
        webserver:
            port: 80/tcp
            negotiable: no



name: hydro
vendor: Alexander Sack <asac@canonical.com>
architecture: [amd64, armhf]
icon: meta/go.png
version: 1.0.7
services:
 - name: webserver
   description: "snappy example: golang mini webserver"
   start: ./magic-bin/go-example-webserver
   caps:
    - networking
    - network-service

