// generated by stringer -type priority; DO NOT EDIT

package hydroctl

import "fmt"

const _priority_name = "priLowpriHighpriAbsolute"

var _priority_index = [...]uint8{0, 6, 13, 24}

func (i priority) String() string {
	if i < 0 || i >= priority(len(_priority_index)-1) {
		return fmt.Sprintf("priority(%d)", i)
	}
	return _priority_name[_priority_index[i]:_priority_index[i+1]]
}
