// Code generated by "stringer -type priority"; DO NOT EDIT.

package hydroctl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[priLow-0]
	_ = x[priHigh-1]
	_ = x[priAbsolute-2]
}

const _priority_name = "priLowpriHighpriAbsolute"

var _priority_index = [...]uint8{0, 6, 13, 24}

func (i priority) String() string {
	if i < 0 || i >= priority(len(_priority_index)-1) {
		return "priority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _priority_name[_priority_index[i]:_priority_index[i+1]]
}
