// generated by stringer -type SlotKind; DO NOT EDIT

package hydroctl

import "fmt"

const _SlotKind_name = "AtLeastAtMostExactly"

var _SlotKind_index = [...]uint8{0, 7, 13, 20}

func (i SlotKind) String() string {
	i -= 1
	if i < 0 || i >= SlotKind(len(_SlotKind_index)-1) {
		return fmt.Sprintf("SlotKind(%d)", i+1)
	}
	return _SlotKind_name[_SlotKind_index[i]:_SlotKind_index[i+1]]
}
