// Code generated by "stringer -trimprefix Loc -type MeterLocation"; DO NOT EDIT.

package hydroreport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocUnknown-0]
	_ = x[LocGenerator-1]
	_ = x[LocNeighbour-2]
	_ = x[LocHere-3]
}

const _MeterLocation_name = "UnknownGeneratorNeighbourHere"

var _MeterLocation_index = [...]uint8{0, 7, 16, 25, 29}

func (i MeterLocation) String() string {
	if i < 0 || i >= MeterLocation(len(_MeterLocation_index)-1) {
		return "MeterLocation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MeterLocation_name[_MeterLocation_index[i]:_MeterLocation_index[i+1]]
}
