// Code generated by "stringer -type measure"; DO NOT EDIT.

package ndmeter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mPhase1Current-1]
	_ = x[mPhase2Current-2]
	_ = x[mPhase3Current-3]
	_ = x[mPhase1Voltage-4]
	_ = x[mPhase2Voltage-5]
	_ = x[mPhase3Voltage-6]
	_ = x[mPhase1PowerFactor-7]
	_ = x[mPhase2PowerFactor-8]
	_ = x[mPhase3PowerFactor-9]
	_ = x[mSystemkvar-10]
	_ = x[mSystemkW-11]
	_ = x[mSystemkWhHighWord-12]
	_ = x[mSystemkWhLowWord-13]
	_ = x[mSystemkvarhHighWord-14]
	_ = x[mSystemkvarhLowWord-15]
	_ = x[mPhase1kW-16]
	_ = x[mPhase2kW-17]
	_ = x[mPhase3kW-18]
	_ = x[mCurrentScale-19]
	_ = x[mVoltsScale-20]
	_ = x[mPowerScale-21]
	_ = x[mEnergyScale-22]
	_ = x[mSystemkWh-23]
	_ = x[mSystemkvarh-24]
}

const _measure_name = "mPhase1CurrentmPhase2CurrentmPhase3CurrentmPhase1VoltagemPhase2VoltagemPhase3VoltagemPhase1PowerFactormPhase2PowerFactormPhase3PowerFactormSystemkvarmSystemkWmSystemkWhHighWordmSystemkWhLowWordmSystemkvarhHighWordmSystemkvarhLowWordmPhase1kWmPhase2kWmPhase3kWmCurrentScalemVoltsScalemPowerScalemEnergyScalemSystemkWhmSystemkvarh"

var _measure_index = [...]uint16{0, 14, 28, 42, 56, 70, 84, 102, 120, 138, 149, 158, 176, 193, 213, 232, 241, 250, 259, 272, 283, 294, 306, 316, 328}

func (i measure) String() string {
	i -= 1
	if i < 0 || i >= measure(len(_measure_index)-1) {
		return "measure(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _measure_name[_measure_index[i]:_measure_index[i+1]]
}
