// Code generated by "stringer -type measure"; DO NOT EDIT

package ndmeter

import "fmt"

const _measure_name = "mPhase1CurrentmPhase2CurrentmPhase3CurrentmPhase1VoltagemPhase2VoltagemPhase3VoltagemPhase1PowerFactormPhase2PowerFactormPhase3PowerFactormSystemkvarmSystemkWmSystemkWhHighWordmSystemkWhLowWordmSystemkvarhHighWordmSystemkvarhLowWordmPhase1kWmPhase2kWmPhase3kWmCurrentScalemVoltsScalemPowerScalemEnergyScalemSystemkWhmSystemkvarh"

var _measure_index = [...]uint16{0, 14, 28, 42, 56, 70, 84, 102, 120, 138, 149, 158, 176, 193, 213, 232, 241, 250, 259, 272, 283, 294, 306, 316, 328}

func (i measure) String() string {
	i -= 1
	if i < 0 || i >= measure(len(_measure_index)-1) {
		return fmt.Sprintf("measure(%d)", i+1)
	}
	return _measure_name[_measure_index[i]:_measure_index[i+1]]
}
